#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Tsc\CatStorageSystem\Commands\HollaCommand;
use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new HollaCommand());

$app->run();
