#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Tsc\CatStorageSystem\Commands\DirectoryCatCommand;
use Tsc\CatStorageSystem\Commands\HollaCommand;
use Tsc\CatStorageSystem\Commands\ListCatCommand;
use Symfony\Component\Console\Application;

$app = new Application();

$app->addCommands([
    new DirectoryCatCommand(),
    new HollaCommand(),
    new ListCatCommand(),
]);

$app->run();
