name: Run Tests

on: [push]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install composer dependencies
        run: composer install -n --prefer-dist

      - name: Run tests
        run: |
          ./vendor/bin/phpunit
          ./vendor/bin/phpcs src --standard=PSR12
